language: elixir
elixir:
  - 1.3.4
  - 1.4.0
otp_release:
  - 19.2
script:
  - mix test
  - MIX_ENV=prod mix do compile, archive.build, archive.install --force
  - MIX_ENV=prod mix dialyzer --halt-exit-status
