language: elixir
elixir:
  - 1.6.3
  - 1.7.3
otp_release:
  - 20.3
  - 21.0
script:
  - mix test --trace
  - MIX_ENV=prod mix do compile --warnings-as-errors, archive.build, archive.install --force
  - mix format --check-formatted
  - MIX_ENV=prod mix dialyzer --halt-exit-status
  - OUTPUT_TESTS=true mix test
branches:
  except:
    - /^[0-9]\.[0-9]/
